export const EstadoTurno = Object.freeze({
    DISPONIBLE: "DISPONIBLE",
    RESERVADO: "RESERVADO",
    CANCELADO: "CANCELADO",
    REALIZADO : "REALIZADO",
    PENDIENTE_CONFIRMACION: "PENDIENTE_CONFIRMACION"
});